### ISSUE TITLE
Calling 'depends_on :foo' is deprecated!

### ISSUE THREAD

**Issue by sjackman** [brewsci/homebrew-science#14]
```
brew tap brewsci/science 2>&1 | grep Calling | sort | uniq -c
  12 Calling 'depends_on ... => :perl' is deprecated!
   3 Calling 'depends_on ... => :python' is deprecated!
   2 Calling 'depends_on :ant' is deprecated!
   1 Calling 'depends_on :emacs' is deprecated!
  39 Calling 'depends_on :fortran' is deprecated!
  27 Calling 'depends_on :mpi' is deprecated!
   2 Calling 'depends_on :mysql' is deprecated!
   1 Calling 'depends_on :perl' is deprecated!
   1 Calling 'depends_on :postgresql' is deprecated!
  15 Calling 'depends_on :python' is deprecated!
  13 Calling 'depends_on :python3' is deprecated!
   1 Calling 'depends_on :ruby' is deprecated!
   1 Calling 'depends_on :tex' is deprecated!
   5 Calling <<-EOS.undent is deprecated!
```

**Comment by biorelated** [comment]
After running `brew update`  I get 

```
Warning: Calling 'depends_on :fortran' is deprecated!
Use 'depends_on "gcc"' instead.
/usr/local/Homebrew/Library/Taps/brewsci/homebrew-science/Formula/poretools.rb:25:in `<class:Poretools>'
Please report this to the brewsci/science tap!

Warning: Calling <<-EOS.undent is deprecated!
Use <<~EOS instead.
/usr/local/Homebrew/Library/Taps/brewsci/homebrew-science/Formula/mafft.rb:23:in `block in <class:Mafft>'
Please report this to the brewsci/science tap!

Warning: Calling <<-EOS.undent is deprecated!
Use <<~EOS instead.
/usr/local/Homebrew/Library/Taps/brewsci/homebrew-science/Formula/mafft.rb:23:in `block in <class:Mafft>'
Please report this to the brewsci/science tap!

Warning: Calling <<-EOS.undent is deprecated!
Use <<~EOS instead.
/usr/local/Homebrew/Library/Taps/brewsci/homebrew-science/Formula/mafft.rb:23:in `block in <class:Mafft>'
Please report this to the brewsci/science tap!
```

**Comment by sjackman** [comment]
Yes, these warnings are expected, and you can ignore them for now. I hopefully have time to address this issue in about a week.

**Comment by zfrenchee** [comment]
Potentially related: 

```
Warning: Calling 'depends_on :python3' is deprecated!
Use 'depends_on "python3"' instead.
/usr/local/Homebrew/Library/Taps/brewsci/homebrew-science/Formula/matplotlib.rb:56:in `<class:Matplotlib>'
Please report this to the brewsci/science tap!
```

**Comment by sjackman** [comment]
Yep, same issue. I'll look into it in one week.

**Comment by sjackman** [comment]
I've fixed this issue.
