### ISSUE TITLE
Problem installing blasr

### ISSUE THREAD

**Issue by jimmayxu** [brewsci/homebrew-science#17]
Hi,

I tried to install blasr on Mac OSX using homebrew but I got this error:

```
brew tap brewsci/science     
brew install blasr
Updating Homebrew...
==> Auto-updated Homebrew!
Updated 2 taps (caskroom/cask, caskroom/versions).
Warning: Calling 'depends_on :mysql' is deprecated!
Use 'depends_on "mysql"' instead.
/usr/local/Homebrew/Library/Taps/brewsci/homebrew-science/Formula/blat.rb:19:in `<class:Blat>'
Please report this to the brewsci/science tap!

Warning: Calling 'depends_on :python3' is deprecated!
Use 'depends_on "python3"' instead.
/usr/local/Homebrew/Library/Taps/brewsci/homebrew-science/Formula/matplotlib.rb:56:in `<class:Matplotlib>'
Please report this to the brewsci/science tap!

Warning: Calling <<-EOS.undent is deprecated!
Use <<~EOS instead.
/usr/local/Homebrew/Library/Taps/brewsci/homebrew-science/Formula/plink.rb:23:in `block in <class:Plink>'
Please report this to the brewsci/science tap!

Warning: Calling <<-EOS.undent is deprecated!
Use <<~EOS instead.
/usr/local/Homebrew/Library/Taps/brewsci/homebrew-science/Formula/plink.rb:23:in `block in <class:Plink>'
Please report this to the brewsci/science tap!

Warning: Calling <<-EOS.undent is deprecated!
Use <<~EOS instead.
/usr/local/Homebrew/Library/Taps/brewsci/homebrew-science/Formula/plink.rb:23:in `block in <class:Plink>'
Please report this to the brewsci/science tap!


Warning: Calling <<-EOS.undent is deprecated!
Use <<~EOS instead.
/usr/local/Homebrew/Library/Taps/brewsci/homebrew-science/Formula/blasr.rb:27:in `block in <class:Blasr>'
Please report this to the brewsci/science tap!

Warning: Calling <<-EOS.undent is deprecated!
Use <<~EOS instead.
/usr/local/Homebrew/Library/Taps/brewsci/homebrew-science/Formula/blasr.rb:27:in `block in <class:Blasr>'
Please report this to the brewsci/science tap!

Warning: Calling <<-EOS.undent is deprecated!
Use <<~EOS instead.
/usr/local/Homebrew/Library/Taps/brewsci/homebrew-science/Formula/blasr.rb:27:in `block in <class:Blasr>'
Please report this to the brewsci/science tap!

Warning: Calling <<-EOS.undent is deprecated!
Use <<~EOS instead.
/usr/local/Homebrew/Library/Taps/brewsci/homebrew-science/Formula/blasr.rb:36:in `block in <class:Blasr>'
Please report this to the brewsci/science tap!

Warning: Calling <<-EOS.undent is deprecated!
Use <<~EOS instead.
/usr/local/Homebrew/Library/Taps/brewsci/homebrew-science/Formula/blasr.rb:36:in `block in <class:Blasr>'
Please report this to the brewsci/science tap!

Warning: Calling <<-EOS.undent is deprecated!
Use <<~EOS instead.
/usr/local/Homebrew/Library/Taps/brewsci/homebrew-science/Formula/blasr.rb:36:in `block in <class:Blasr>'
Please report this to the brewsci/science tap!

==> Installing blasr from brewsci/science
Warning: Calling <<-EOS.undent is deprecated!
Use <<~EOS instead.
/usr/local/Homebrew/Library/Taps/brewsci/homebrew-science/Formula/blasr.rb:27:in `block in <class:Blasr>'
Please report this to the brewsci/science tap!

Warning: Calling <<-EOS.undent is deprecated!
Use <<~EOS instead.
/usr/local/Homebrew/Library/Taps/brewsci/homebrew-science/Formula/blasr.rb:27:in `block in <class:Blasr>'
Please report this to the brewsci/science tap!

Warning: Calling <<-EOS.undent is deprecated!
Use <<~EOS instead.
/usr/local/Homebrew/Library/Taps/brewsci/homebrew-science/Formula/blasr.rb:27:in `block in <class:Blasr>'
Please report this to the brewsci/science tap!

Warning: Calling <<-EOS.undent is deprecated!
Use <<~EOS instead.
/usr/local/Homebrew/Library/Taps/brewsci/homebrew-science/Formula/blasr.rb:36:in `block in <class:Blasr>'
Please report this to the brewsci/science tap!

Warning: Calling <<-EOS.undent is deprecated!
Use <<~EOS instead.
/usr/local/Homebrew/Library/Taps/brewsci/homebrew-science/Formula/blasr.rb:36:in `block in <class:Blasr>'
Please report this to the brewsci/science tap!

Warning: Calling <<-EOS.undent is deprecated!
Use <<~EOS instead.
/usr/local/Homebrew/Library/Taps/brewsci/homebrew-science/Formula/blasr.rb:36:in `block in <class:Blasr>'
Please report this to the brewsci/science tap!

==> Downloading https://github.com/PacificBiosciences/blasr/archive/smrtanalysis
Already downloaded: /Users/cr517/Library/Caches/Homebrew/blasr-2.2.tar.gz
==> make STATIC= HDF5INCLUDEDIR=/usr/local/opt/hdf5/include HDF5LIBDIR=/usr/loca
Last 15 lines from /Users/cr517/Library/Logs/Homebrew/blasr/01.make:
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/memory:4912:1: note: candidate template ignored: could not match 'shared_ptr<type-parameter-0-0>' against 'const RegionAnnotation'
operator<(const shared_ptr<_Tp>& __x, const shared_ptr<_Up>& __y) _NOEXCEPT
^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/memory:4977:1: note: candidate template ignored: could not match 'shared_ptr<type-parameter-0-0>' against 'const RegionAnnotation'
operator<(const shared_ptr<_Tp>& __x, nullptr_t) _NOEXCEPT
^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/memory:4985:1: note: candidate template ignored: could not match 'shared_ptr<type-parameter-0-0>' against 'const int'
operator<(nullptr_t, const shared_ptr<_Tp>& __x) _NOEXCEPT
^
1 error generated.
make[1]: *** [bin/KBandMatcher.o] Error 1
make: *** [alignment-build] Error 2
make: *** [sequtils-build] Error 2
clang++  -O3 -Wno-div-by-zero -I ..//common -I /usr/local/opt/hdf5/include bin/PrintPBBWT.o -o bin/bwtpbPrint -L/usr/local/opt/hdf5/lib -lz -lpthread
clang++  -O3 -Wno-div-by-zero -I ..//common -I /usr/local/opt/hdf5/include bin/BWTQuery.o -o bin/bwtquery -L/usr/local/opt/hdf5/lib -lz -lpthread

If reporting this issue please do so at (not Homebrew/brew or Homebrew/core):
https://github.com/brewsci/homebrew-science/issues
```

**Comment by sjackman** [comment]
Please enclose copy-and-paste blocks in triple back ticks.
See https://help.github.com/articles/basic-writing-and-formatting-syntax/#quoting-code

**Comment by sjackman** [comment]
Try…
```sh
brew install --force-bottle blasr
brew test blasr
```

**Comment by sjackman** [comment]
That sadly didn't work for me.
```
❯❯❯ blasr
dyld: Library not loaded: /Users/sjackman/.homebrew/lib/libhdf5_cpp.9.dylib
  Referenced from: /usr/local/Cellar/blasr/2.2/bin/blasr
  Reason: image not found
```

**Comment by sjackman** [comment]
This tap Homebrew/science is retired and unsupported. If you're able to resolve this issue, consider submitting this formula to https://github.com/brewsci/homebrew-bio
