### ISSUE TITLE
Issue while tapping in brewsci/science on travis

### ISSUE THREAD

**Issue by Joschka1** [brewsci/homebrew-science#189]
I'm using brew bundle on travis ci and tapping into the brewsci/science tap results in following issue: 
```==> Tapping brewsci/science
Cloning into '/usr/local/Homebrew/Library/Taps/brewsci/homebrew-science'...
Error: Invalid formula: /usr/local/Homebrew/Library/Taps/brewsci/homebrew-science/Formula/ome-common.rb
Error: Invalid formula: /usr/local/Homebrew/Library/Taps/brewsci/homebrew-science/Formula/ome-files.rb
Error: Invalid formula: /usr/local/Homebrew/Library/Taps/brewsci/homebrew-science/Formula/ome-xml.rb
Error: Invalid formula: /usr/local/Homebrew/Library/Taps/brewsci/homebrew-science/Formula/osgearth.rb
Error: Cannot tap brewsci/science: invalid syntax in tap!
uninitialized constant #<Class:0x0000000101e9c9b8>::MinimumMacOSRequirement
Did you mean?  MaximumMacOSRequirement
uninitialized constant #<Class:0x0000000101e0c020>::MinimumMacOSRequirement
Did you mean?  MaximumMacOSRequirement
uninitialized constant #<Class:0x000000010148fda8>::MinimumMacOSRequirement
Did you mean?  MaximumMacOSRequirement
uninitialized constant #<Class:0x0000000101b46cc8>::MinimumMacOSRequirement
Did you mean?  MaximumMacOSRequirement
Tapping brewsci/science has failed!```

Best, 
Joschka

**Comment by jonchang** [comment]
Hi @Joschka1 thanks for the heads up. I've added a pull request to address this issue. I also recommend moving the formulae you require from this tap into either a tap that you maintain yourself, or if applicable one of the other brewsci taps. This tap is not maintained so if you depend on it for your travis CI you will continue to see issues like this in the future.

**Comment by wookoouk** [comment]
I am getting the same issue when running `brew outdated` or `brew upgrade`

```
[pagem@software ~]$ brew outdated
Error: uninitialized constant #<Class:0x0000000003fc4dd0>::MinimumMacOSRequirement
Did you mean?  MaximumMacOSRequirement
Please report this bug:
  https://github.com/Linuxbrew/brew/wiki/troubleshooting
/tsl/software/testing/brew/default/x86_64/opt/nanopolish/.brew/nanopolish.rb:19:in `<class:Nanopolish>'
/tsl/software/testing/brew/default/x86_64/opt/nanopolish/.brew/nanopolish.rb:1:in `load_formula'
/tsl/software/testing/brew/default/x86_64/Library/Homebrew/formulary.rb:26:in `module_eval'
/tsl/software/testing/brew/default/x86_64/Library/Homebrew/formulary.rb:26:in `load_formula'
/tsl/software/testing/brew/default/x86_64/Library/Homebrew/formulary.rb:46:in `load_formula_from_path'
/tsl/software/testing/brew/default/x86_64/Library/Homebrew/formulary.rb:95:in `load_file'
/tsl/software/testing/brew/default/x86_64/Library/Homebrew/formulary.rb:86:in `klass'
/tsl/software/testing/brew/default/x86_64/Library/Homebrew/formulary.rb:82:in `get_formula'
/tsl/software/testing/brew/default/x86_64/Library/Homebrew/formulary.rb:275:in `factory'
/tsl/software/testing/brew/default/x86_64/Library/Homebrew/formulary.rb:316:in `rescue in from_keg'
/tsl/software/testing/brew/default/x86_64/Library/Homebrew/formulary.rb:312:in `from_keg'
/tsl/software/testing/brew/default/x86_64/Library/Homebrew/formulary.rb:289:in `from_rack'
/tsl/software/testing/brew/default/x86_64/Library/Homebrew/formula.rb:1408:in `block in installed'
/tsl/software/testing/brew/default/x86_64/Library/Homebrew/formula.rb:1406:in `each'
/tsl/software/testing/brew/default/x86_64/Library/Homebrew/formula.rb:1406:in `flat_map'
/tsl/software/testing/brew/default/x86_64/Library/Homebrew/formula.rb:1406:in `installed'
/tsl/software/testing/brew/default/x86_64/Library/Homebrew/cmd/outdated.rb:28:in `outdated'
/tsl/software/testing/brew/default/x86_64/Library/Homebrew/brew.rb:100:in `<main>'
```
