### ISSUE TITLE
emboss: Error: no implicit conversion of Symbol into String

### ISSUE THREAD

**Issue by LeeBergstrand** [brewsci/homebrew-science#22]
Produced in the linuxbrew docker container.

```shell
brew install emboss

Warning: Calling 'depends_on :postgresql' is deprecated!
Use 'depends_on "postgresql"' instead.
/home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/brewsci/homebrew-science/Formula/emboss.rb:22:in `<class:Emboss>'
Please report this to the brewsci/science tap!

Warning: Calling 'depends_on :mysql' is deprecated!
Use 'depends_on "mysql"' instead.

/home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/brewsci/homebrew-science/Formula/emboss.rb:23:in `<class:Emboss>'
Please report this to the brewsci/science tap!
==> Installing emboss from brewsci/science
Error: no implicit conversion of Symbol into String
Please report this bug:
  https://github.com/Linuxbrew/brew/blob/master/docs/Troubleshooting.md#troubleshooting
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/formulary.rb:363:in `extname'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/formulary.rb:363:in `loader_for'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/formulary.rb:280:in `factory'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/dependency.rb:33:in `to_formula'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/formula_installer.rb:498:in `block in expand_dependencies'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/dependency.rb:109:in `block in action'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/dependency.rb:107:in `catch'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/dependency.rb:107:in `action'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/dependency.rb:86:in `block in expand'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/dependency.rb:83:in `each'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/dependency.rb:83:in `expand'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/formula_installer.rb:492:in `expand_dependencies'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/formula_installer.rb:379:in `compute_dependencies'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/formula_installer.rb:134:in `verify_deps_exist'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/formula_installer.rb:127:in `prelude'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/cmd/install.rb:371:in `install_formula'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/cmd/install.rb:227:in `block in install'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/cmd/install.rb:225:in `each'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/cmd/install.rb:225:in `install'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/brew.rb:100:in `<main>'
```

**Comment by LeeBergstrand** [comment]
Some sort of ruby error.

**Comment by LeeBergstrand** [comment]
@sjackman Is it okay to open issues like this in this repo? or do we have to wait for the formula to be ported over to ```brewsci/bio```?

**Comment by sjackman** [comment]
It's fine to report the issue here. I may or may not fix it. Best if possible is to open a PR to submit the formula to Brewsci/bio.

As a workaround for now, `brew edit emboss` and delete the lines
```ruby
  depends_on :postgresql  => :optional
  depends_on :mysql       => :optional
```

**Comment by LeeBergstrand** [comment]
Thanks !

**Comment by LeeBergstrand** [comment]
@sjackman Thanks!
