### ISSUE TITLE
mumps: dynamiclib: No such file or directory

### ISSUE THREAD

**Issue by floswald** [brewsci/homebrew-science#24]
hi there,
i've seen the message about this not being maintained. i can't find this formula anywhere else though, where should I post this issue? thanks

```
➜  Students git:(master) brew install ipopt
Warning: Calling 'depends_on :fortran' is deprecated!
Use 'depends_on "gcc"' instead.
/usr/local/Homebrew/Library/Taps/brewsci/homebrew-science/Formula/ipopt.rb:21:in `<class:Ipopt>'
Please report this to the brewsci/science tap!

==> Installing ipopt from brewsci/science
Warning: Calling 'depends_on :mpi' is deprecated!
Use 'depends_on "open-mpi"' instead.
/usr/local/Homebrew/Library/Taps/brewsci/homebrew-science/Formula/mumps.rb:11:in `<class:Mumps>'
Please report this to the brewsci/science tap!

==> Installing dependencies for brewsci/science/ipopt: mumps
==> Installing brewsci/science/ipopt dependency: mumps
Warning: Calling 'depends_on :mpi' is deprecated!
Use 'depends_on "open-mpi"' instead.
/usr/local/Homebrew/Library/Taps/brewsci/homebrew-science/Formula/mumps.rb:11:in `<class:Mumps>'
Please report this to the brewsci/science tap!

Warning: Calling 'depends_on :fortran' is deprecated!
Use 'depends_on "gcc"' instead.
/usr/local/Homebrew/Library/Taps/brewsci/homebrew-science/Formula/mumps.rb:14:in `<class:Mumps>'
Please report this to the brewsci/science tap!

==> Downloading http://mumps.enseeiht.fr/MUMPS_5.1.1.tar.gz
######################################################################## 100.0%
==> make alllib LIBEXT=.dylib AR= -dynamiclib -Wl,-install_name -Wl,/usr/local/Cellar/mumps/5.1.1_1/lib/$(notdir $@) -undefined dynamic_lookup -o  RANLIB=echo 
Last 15 lines from /Users/florian.oswald/Library/Logs/Homebrew/mumps/01.make:
clang -fPIC -I../include -O  -c symbfac.c -o symbfac.o
clang -fPIC -I../include -O  -c interface.c -o interface.o
clang -fPIC -I../include -O  -c sort.c -o sort.o
clang -fPIC -I../include -O  -c minpriority.c -o minpriority.o
dynamiclib -Wl,-install_name -Wl,/usr/local/Cellar/mumps/5.1.1_1/lib/libpord.dylib -undefined dynamic_lookup -o libpord.dylib graph.o gbipart.o gbisect.o ddcreate.o ddbisect.o nestdiss.o multisector.o gelim.o bucket.o tree.o symbfac.o interface.o sort.o minpriority.o 
make[2]: dynamiclib: No such file or directory
make[2]: [libpord.dylib] Error 1 (ignored)
echo libpord.dylib
libpord.dylib
if [ "./PORD/lib/" != "" ] ; then \
	  cp ./PORD/lib//libpord.dylib lib/libpord.dylib; \
	fi;
cp: ./PORD/lib//libpord.dylib: No such file or directory
make[1]: *** [lib/libpord.dylib] Error 1
make: *** [c] Error 2

If reporting this issue please do so at (not Homebrew/brew or Homebrew/core):
https://github.com/brewsci/homebrew-science/issues
```

**Comment by sjackman** [comment]
Here you are!
https://github.com/dpo/homebrew-openblas/blob/master/mumps.rb

**Comment by floswald** [comment]
fastest issue ever. thanks!
