### ISSUE TITLE
maker installation: installed perl dependencies not being recognized

### ISSUE THREAD

**Issue by ckeeling** [brewsci/homebrew-science#26]
This issue originated in [https://github.com/bcgsc/orca/issues/44](https://github.com/bcgsc/orca/issues/44) but this is not specific to orca or Singularity.

I installed all the perl dependencies with cpanm and can confirm they are to be found in: ~/.linuxbrew/Cellar/perl/5.26.1/lib/perl5/5.26.1/
`export PERL_LOCAL_LIB_ROOT="~/.linuxbrew/Cellar/perl/5.26.1/lib/perl5/5.26.1"`

`brew update`
Already up-to-date.

They are available, e.g.
`perl -e 'use PerlIO::gzip'`
(no error)

`brew install brewsci/homebrew-science/maker`
```
Warning: Calling 'depends_on :mpi' is deprecated!
Use 'depends_on "open-mpi"' instead.
/home/ckeeling/.linuxbrew/Homebrew/Library/Taps/brewsci/homebrew-science/Formula/maker.rb:14:in `<class:Maker>'
Please report this to the brewsci/science tap!

Warning: Calling 'depends_on ... => :perl' is deprecated!
There is no replacement.
/home/ckeeling/.linuxbrew/Homebrew/Library/Taps/brewsci/homebrew-science/Formula/maker.rb:23:in `<class:Maker>'
Please report this to the brewsci/science tap!

Warning: Calling 'depends_on ... => :perl' is deprecated!
There is no replacement.
/home/ckeeling/.linuxbrew/Homebrew/Library/Taps/brewsci/homebrew-science/Formula/maker.rb:24:in `<class:Maker>'
Please report this to the brewsci/science tap!

Warning: Calling 'depends_on ... => :perl' is deprecated!
There is no replacement.
/home/ckeeling/.linuxbrew/Homebrew/Library/Taps/brewsci/homebrew-science/Formula/maker.rb:25:in `<class:Maker>'
Please report this to the brewsci/science tap!

Warning: Calling 'depends_on ... => :perl' is deprecated!
There is no replacement.
/home/ckeeling/.linuxbrew/Homebrew/Library/Taps/brewsci/homebrew-science/Formula/maker.rb:26:in `<class:Maker>'
Please report this to the brewsci/science tap!

Warning: Calling 'depends_on ... => :perl' is deprecated!
There is no replacement.
/home/ckeeling/.linuxbrew/Homebrew/Library/Taps/brewsci/homebrew-science/Formula/maker.rb:27:in `<class:Maker>'
Please report this to the brewsci/science tap!

Warning: Calling 'depends_on ... => :perl' is deprecated!
There is no replacement.
/home/ckeeling/.linuxbrew/Homebrew/Library/Taps/brewsci/homebrew-science/Formula/maker.rb:28:in `<class:Maker>'
Please report this to the brewsci/science tap!

Warning: Calling 'depends_on ... => :perl' is deprecated!
There is no replacement.
/home/ckeeling/.linuxbrew/Homebrew/Library/Taps/brewsci/homebrew-science/Formula/maker.rb:29:in `<class:Maker>'
Please report this to the brewsci/science tap!

Warning: Calling 'depends_on ... => :perl' is deprecated!
There is no replacement.
/home/ckeeling/.linuxbrew/Homebrew/Library/Taps/brewsci/homebrew-science/Formula/maker.rb:30:in `<class:Maker>'
Please report this to the brewsci/science tap!

Warning: Calling 'depends_on ... => :perl' is deprecated!
There is no replacement.
/home/ckeeling/.linuxbrew/Homebrew/Library/Taps/brewsci/homebrew-science/Formula/maker.rb:32:in `<class:Maker>'
Please report this to the brewsci/science tap!

Warning: Calling 'depends_on ... => :perl' is deprecated!
There is no replacement.
/home/ckeeling/.linuxbrew/Homebrew/Library/Taps/brewsci/homebrew-science/Formula/maker.rb:33:in `<class:Maker>'
Please report this to the brewsci/science tap!

Warning: Calling 'depends_on ... => :perl' is deprecated!
There is no replacement.
/home/ckeeling/.linuxbrew/Homebrew/Library/Taps/brewsci/homebrew-science/Formula/maker.rb:34:in `<class:Maker>'
Please report this to the brewsci/science tap!

Warning: Calling 'depends_on ... => :perl' is deprecated!
There is no replacement.
/home/ckeeling/.linuxbrew/Homebrew/Library/Taps/brewsci/homebrew-science/Formula/maker.rb:35:in `<class:Maker>'
Please report this to the brewsci/science tap!

==> Installing maker from brewsci/science
maker: Unsatisfied dependency: Bio::Perl
Homebrew does not provide special Perl dependencies; install with:
  `cpan -i Bio::Perl`
maker: Unsatisfied dependency: Bit::Vector
Homebrew does not provide special Perl dependencies; install with:
  `cpan -i Bit::Vector`
maker: Unsatisfied dependency: DBD::SQLite
Homebrew does not provide special Perl dependencies; install with:
  `cpan -i DBD::SQLite`
maker: Unsatisfied dependency: DBI
Homebrew does not provide special Perl dependencies; install with:
  `cpan -i DBI`
maker: Unsatisfied dependency: File::Which
Homebrew does not provide special Perl dependencies; install with:
  `cpan -i File::Which`
maker: Unsatisfied dependency: IO::All
Homebrew does not provide special Perl dependencies; install with:
  `cpan -i IO::All`
maker: Unsatisfied dependency: IO::Prompt
Homebrew does not provide special Perl dependencies; install with:
  `cpan -i IO::Prompt`
maker: Unsatisfied dependency: Inline::C
Homebrew does not provide special Perl dependencies; install with:
  `cpan -i Inline::C`
maker: Unsatisfied dependency: Perl::Unsafe::Signals
Homebrew does not provide special Perl dependencies; install with:
  `cpan -i Perl::Unsafe::Signals`
maker: Unsatisfied dependency: PerlIO::gzip
Homebrew does not provide special Perl dependencies; install with:
  `cpan -i PerlIO::gzip`
maker: Unsatisfied dependency: forks
Homebrew does not provide special Perl dependencies; install with:
  `cpan -i forks`
maker: Unsatisfied dependency: forks::shared
Homebrew does not provide special Perl dependencies; install with:
  `cpan -i forks::shared`
Error: Unsatisfied requirements failed this build.
```

**Comment by sjackman** [comment]
Please enclose copy-and-paste blocks in triple back ticks.
See https://help.github.com/articles/basic-writing-and-formatting-syntax/#quoting-code

**Comment by sjackman** [comment]
Just today I fixed https://github.com/brewsci/homebrew-science/issues/14
Can you try this again?

**Comment by ckeeling** [comment]
Different, but not working yet.

`brew install brewsci/homebrew-science/maker`
```==> Installing maker from brewsci/science
==> Downloading http://yandell.topaz.genetics.utah.edu/maker_downloads/static/maker-2.31.9.tgz
Already downloaded: /home/ckeeling/.cache/Homebrew/maker-2.31.9.tgz
==> (echo no; yes '') |perl Build.PL
==> ./Build install
Last 15 lines from /home/ckeeling/.cache/Homebrew/Logs/maker/02.Build:
2018-02-05 18:27:38 -0800

./Build
install


* MISSING MAKER PREREQUISITES - CANNOT CONTINUE!!
Building MAKER

If reporting this issue please do so at (not Homebrew/brew or Homebrew/core):
https://github.com/brewsci/homebrew-science/issues

These open issues may also help:
maker installation: installed perl dependencies not being recognized https://github.com/brewsci/homebrew-science/issues/26```

**Comment by sjackman** [comment]
I don't suppose MAKER is kind enough to tell you which prerequisites it's missing?

**Comment by ckeeling** [comment]
That would be nice!  In ```/home/ckeeling/.cache/Homebrew/Logs/maker/``` there are three files:
```00.options.out  '01.(echo'  02.Build``` which look kind of weird.  Do these make sense to you?  Is something wrong in the formula around line 40?

`cat '01.(echo'`
```2018-02-05 18:27:37 -0800

(echo no; yes '') |perl Build.PL

Checking prerequisites...
  requires:
    !  Bio::Root::Version is not installed
    !  Bit::Vector is not installed
    !  DBD::SQLite is not installed
    !  IO::All is not installed
    !  Inline::C is not installed
    !  Perl::Unsafe::Signals is not installed
    !  Want is not installed
    !  forks is not installed
    !  forks::shared is not installed
  build_requires:
    !  DBI is not installed
    !  ExtUtils::CBuilder is not installed
    !  LWP::Simple is not installed
    !  Test::More is not installed
  recommends:
    *  DBD::Pg is not installed

ERRORS/WARNINGS FOUND IN PREREQUISITES.  You may wish to install the versions
of the modules indicated above before proceeding with this installation

Run 'Build installdeps' to install missing prerequisites.


MAKER supports distributed parallelization via MPI.
Would you like to configure MAKER for MPI (This
requires that you have an MPI client installed)? [N ]Creating new 'MYMETA.yml' with configuration results
Creating new 'Build' script for 'MAKER' version 'v2.31.9'


The file 'Build' has been created for you to finish installing MAKER.


==============================================================================
STATUS MAKER v2.31.9
==============================================================================
PERL Dependencies:	MISSING
		  !  IO::All
		  !  forks::shared
		  !  DBD::SQLite
		  !  Bio::Root::Version
		  !  Inline::C
		  !  forks
		  !  Bit::Vector
		  !  Want
		  !  Perl::Unsafe::Signals

External Programs:	VERIFIED
External C Libraries:	VERIFIED
MPI SUPPORT:		DISABLED
MWAS Web Interface:	DISABLED
MAKER PACKAGE:		MISSING PREREQUISITES


Important Commands:
	./Build installdeps	#installs missing PERL dependencies
	./Build installexes	#installs all missing external programs
	./Build install		#installs MAKER
	./Build status		#Shows this status menu

Other Commands:
	./Build repeatmasker	#installs RepeatMasker (asks for RepBase)
	./Build blast		#installs BLAST (NCBI BLAST+)
	./Build exonerate	#installs Exonerate (v2 on UNIX / v1 on Mac OSX)
	./Build snap		#installs SNAP
	./Build augustus	#installs Augustus
	./Build apollo		#installs Apollo
	./Build gbrowse		#installs GBrowse (must be root)
	./Build jbrowse		#installs JBrowse (MAKER copy, not web accecible)
	./Build webapollo	#installs WebApollo (use maker2wap to create DBs)
	./Build mpich2		#installs MPICH2 (but manual install recommended)
```

It looks like the Perl modules still.

**Comment by ckeeling** [comment]
`perldoc -l IO::All forks::shared DBD::SQLite Bio::Root::Version Inline::C forks Bit::Vector Want Perl::Unsafe::Signals`

```/home/ckeeling/.linuxbrew/Cellar/perl/5.26.1/lib/perl5/site_perl/5.26.1/IO/All.pod
/home/ckeeling/.linuxbrew/Cellar/perl/5.26.1/lib/perl5/site_perl/5.26.1/x86_64-linux-thread-multi/forks/shared.pm
/home/ckeeling/.linuxbrew/Cellar/perl/5.26.1/lib/perl5/site_perl/5.26.1/x86_64-linux-thread-multi/DBD/SQLite.pm
/home/ckeeling/.linuxbrew/Cellar/perl/5.26.1/lib/perl5/site_perl/5.26.1/Bio/Root/Version.pm
/home/ckeeling/.linuxbrew/Cellar/perl/5.26.1/lib/perl5/site_perl/5.26.1/Inline/C.pod
/home/ckeeling/.linuxbrew/Cellar/perl/5.26.1/lib/perl5/site_perl/5.26.1/x86_64-linux-thread-multi/forks.pm
/home/ckeeling/.linuxbrew/Cellar/perl/5.26.1/lib/perl5/site_perl/5.26.1/x86_64-linux-thread-multi/Bit/Vector.pod
/home/ckeeling/.linuxbrew/Cellar/perl/5.26.1/lib/perl5/site_perl/5.26.1/x86_64-linux-thread-multi/Want.pm
/home/ckeeling/.linuxbrew/Cellar/perl/5.26.1/lib/perl5/site_perl/5.26.1/x86_64-linux-thread-multi/Perl/Unsafe/Signals.pm
```

**Comment by sjackman** [comment]
Try `brew edit maker` and add
```ruby
depends_on "perl"
```

**Comment by ckeeling** [comment]
Yes!  That did the trick, thanks @sjackman

**Comment by sjackman** [comment]
Woohoo! I'll add that to the formula.

**Comment by sjackman** [comment]
Fixed by https://github.com/brewsci/homebrew-science/pull/28
